import type { LayoutStyle, Technology, TechnologyInput } from "./types";

function tech(
  partial: Omit<TechnologyInput, "active"> & { active?: boolean },
): TechnologyInput {
  return { active: true, ...partial };
}

export const DEFAULT_TECHNOLOGIES: TechnologyInput[] = [
  tech({
    id: "servicenow",
    name: "ServiceNow",
    slug: "servicenow",
    tagline: "Platform navigator aesthetic",
    description: "Dark instance UI with filter bar and module sidebar.",
    layout: "platform-dark",
    colors: {
      background: "#18181f",
      surface: "#2a2a33",
      accent: "#86ee78",
      accentText: "#0c1220",
      text: "#f5f5f5",
      muted: "#cfcfcf",
      cardHeader: "#6fa894",
      cardBody: "#d9d9d9",
      sidebar: "#1f1f27",
    },
  }),
  tech({
    id: "salesforce",
    name: "Salesforce",
    slug: "salesforce",
    tagline: "Lightning workspace",
    description: "Cloud-blue Lightning layout for admins and developers.",
    layout: "cloud-blue",
    colors: {
      background: "#eaf5fb",
      surface: "#ffffff",
      accent: "#0176d3",
      accentText: "#ffffff",
      text: "#16325c",
      muted: "#54698d",
      cardHeader: "#032d60",
      cardBody: "#ffffff",
      sidebar: "#f4f6f9",
    },
  }),
  tech({
    id: "aws",
    name: "AWS",
    slug: "aws",
    tagline: "Console-inspired",
    description: "AWS console dark palette with orange accents.",
    layout: "console-dark",
    colors: {
      background: "#232f3e",
      surface: "#37475a",
      accent: "#ff9900",
      accentText: "#111111",
      text: "#f2f3f3",
      muted: "#d5dbdb",
      cardHeader: "#37475a",
      cardBody: "#2d3a4a",
      sidebar: "#1b242f",
    },
  }),
  tech({
    id: "azure",
    name: "Microsoft Azure",
    slug: "azure",
    tagline: "Portal clarity",
    description: "Clean Azure portal light theme.",
    layout: "portal-light",
    colors: {
      background: "#f3f6fb",
      surface: "#ffffff",
      accent: "#0078d4",
      accentText: "#ffffff",
      text: "#201f1e",
      muted: "#605e5c",
      cardHeader: "#0078d4",
      cardBody: "#ffffff",
      sidebar: "#eef3f9",
    },
  }),
  tech({
    id: "react",
    name: "React / Frontend",
    slug: "react",
    tagline: "Modern product UI",
    description: "Clean modern layout for frontend and React engineers.",
    layout: "modern-clean",
    colors: {
      background: "#0b1220",
      surface: "#121a2b",
      accent: "#61dafb",
      accentText: "#0b1220",
      text: "#eef3ff",
      muted: "#a9b6d3",
      cardHeader: "#1a2740",
      cardBody: "#f4f7ff",
      sidebar: "#0f1726",
    },
  }),
  tech({
    id: "java",
    name: "Java / Spring",
    slug: "java",
    tagline: "Enterprise engineering",
    description: "Crisp enterprise look for Java and Spring specialists.",
    layout: "modern-clean",
    colors: {
      background: "#f7f4ef",
      surface: "#ffffff",
      accent: "#e76f00",
      accentText: "#ffffff",
      text: "#1c1917",
      muted: "#57534e",
      cardHeader: "#292524",
      cardBody: "#ffffff",
      sidebar: "#fff7ed",
    },
  }),
  tech({
    id: "python",
    name: "Python / Data",
    slug: "python",
    tagline: "Data & backend clarity",
    description: "Readable layout for Python, data, and ML engineers.",
    layout: "modern-clean",
    colors: {
      background: "#1e293b",
      surface: "#273549",
      accent: "#3776ab",
      accentText: "#ffffff",
      text: "#f8fafc",
      muted: "#cbd5e1",
      cardHeader: "#ffd343",
      cardBody: "#f8fafc",
      sidebar: "#0f172a",
    },
  }),
  tech({
    id: "kubernetes",
    name: "Kubernetes / DevOps",
    slug: "kubernetes",
    tagline: "Cloud-native ops",
    description: "Terminal-inspired theme for DevOps and platform engineers.",
    layout: "terminal",
    colors: {
      background: "#0a0f14",
      surface: "#111820",
      accent: "#326ce5",
      accentText: "#ffffff",
      text: "#e6edf5",
      muted: "#9fb0c3",
      cardHeader: "#16325c",
      cardBody: "#dbe7f5",
      sidebar: "#071018",
    },
  }),
  tech({
    id: "sap",
    name: "SAP",
    slug: "sap",
    tagline: "Enterprise ERP",
    description: "Business-blue theme for SAP consultants and ABAP developers.",
    layout: "portal-light",
    colors: {
      background: "#f5f7fa",
      surface: "#ffffff",
      accent: "#0faaff",
      accentText: "#ffffff",
      text: "#1a2733",
      muted: "#5b6b7c",
      cardHeader: "#008fd3",
      cardBody: "#ffffff",
      sidebar: "#eaf4fb",
    },
  }),
  tech({
    id: "devops",
    name: "DevOps / SRE",
    slug: "devops",
    tagline: "Reliability first",
    description: "Dark terminal theme for SRE and DevOps resumes.",
    layout: "terminal",
    colors: {
      background: "#101418",
      surface: "#171d23",
      accent: "#3dd68c",
      accentText: "#0b1210",
      text: "#e8f0ea",
      muted: "#9db0a5",
      cardHeader: "#1f6f5b",
      cardBody: "#e7f5ee",
      sidebar: "#0c1014",
    },
  }),
];

export const LAYOUT_OPTIONS: { id: LayoutStyle; label: string; hint: string }[] =
  [
    { id: "platform-dark", label: "Platform Dark", hint: "ServiceNow-style navigator" },
    { id: "cloud-blue", label: "Cloud Blue", hint: "Salesforce Lightning feel" },
    { id: "console-dark", label: "Console Dark", hint: "AWS-style console" },
    { id: "portal-light", label: "Portal Light", hint: "Azure/SAP portal" },
    { id: "modern-clean", label: "Modern Clean", hint: "Product / engineering" },
    { id: "terminal", label: "Terminal", hint: "DevOps / cloud-native" },
  ];

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
